### ISSUE TITLE
Traducción de venv.rst

### ISSUE THREAD

**Issue by humitos** [PyAr/tutorial#15]
La versión 3.5 del tutorial de Python incluye un archivo nuevo llamado `venv.py` que explica sobre cómo crear entornos virtuales.

https://hg.python.org/cpython/file/v3.5.0/Doc/tutorial/venv.rst

Deberíamos agregarlo y traducirlo.

**Comment by gamba47** [comment]
Donde se puede crear este archivo? hay que hacer uno nuevo y después hago un pull request del archivo?

Saludos!

**Comment by humitos** [comment]
Deberías copiar el archivo `original/venv.rst` (desde master) a la carpeta `traducidos/venv.rst` y comenzar con la traducción.

Cuando lo tengas listo, hacés un PR, yo compilo el sitio, hago los cambios que necesite para que funcione, te lo comento, hacés esos cambios, acepto el PR y publicamos la nueva versión ;)

**Comment by omicronvt** [comment]
Muuuy nuevo en github, ya lo traduje. Como hago el PR ? Saludos

**Comment by gamba47** [comment]
@omicronvt esto quizás te puede ayudar https://styde.net/pull-request-en-github/

Soy tan novato que no se bien como guiarte.

Saludos.
gamba47 - Emiliano.

**Comment by humitos** [comment]
@omicronvt tenés que hacer un fork de este repo. Luego, si ya tenés el archivo "venv.rst" traducido, tenés que sobreescribirlo en el directorio del repo. Luego "git commit" y finalmente "git push".

Después entrás a esta página de github (de este repo) y te va a aparecer un botón que dice "Propose Pull Request" o similar. Dale click y ya :D
