### ISSUE TITLE
Faltan varias dependencias

### ISSUE THREAD

**Issue by nicopace** [PyAr/tutorial#17]
Buenas tardes,
Tratando de compilar el epub, me descargué el repo y noté que necesita varios comandos adicionales además de los que dice el tutorial.

Esto es lo que tuve que hacer adicional:
apt install inkscape
pip install fabric bs4
pip install feedparser configparser

Por favor, testear que no lo chequeé exhaustivamente.

**Comment by fdemian** [comment]
Buenas, me paso algo parecido. Al final lo hice funcionar instalando varios paquetes en el SSOO y de python. Los requerimientos que me genera pip freeze son estos (en principio lo instale en una VM limpia asi que deberían ser exactamente estos).

Babel==2.3.4
BzrTools==2.6.0
Fabric==1.13.1
Jinja2==2.9.5
MarkupSafe==0.23
Pillow==4.0.0
Pygments==2.2.0
SecretStorage==2.0.0
Sphinx==1.5.2
alabaster==0.7.9
argparse==1.2.1
beautifulsoup4==4.5.3
bs4==0.0.1
bzr==2.7.0dev1
chardet==2.0.1
colorama==0.2.5
configobj==4.7.2
configparser==3.5.0
docutils==0.13.1
duplicity==0.6.23
feedparser==5.2.1
html5lib==0.999
httplib2==0.8
imagesize==0.7.1
keyring==3.5
launchpadlib==1.10.2
lazr.restfulclient==0.13.3
lazr.uri==1.0.3
lockfile==0.8
mercurial==2.8.2
oauth==1.0.1
olefile==0.44
paramiko==1.10.1
pdfrw==0.3
pycrypto==2.6.1
pygobject==3.12.0
pygpgme==0.3
python-apt==0.9.3.5ubuntu2
pytz==2016.10
reportlab==3.3.0
requests==2.13.0
rst2pdf==0.93.dev
simplejson==3.3.1
six==1.5.2
snowballstemmer==1.2.1
sphinx-bootstrap-theme==0.4.13
urllib3==1.7.1
wadllib==1.3.2
wheel==0.24.0
wsgiref==0.1.2
zope.interface==4.0.5
