### ISSUE TITLE
Crear ebook

### ISSUE THREAD

**Issue by humitos** [PyAr/tutorial#9]
Hacer una versión ebook para celulares y otros.

**Comment by neyder** [comment]
Trabajando en ello

**Comment by juancarlospaco** [comment]
There you go:
https://gist.github.com/juancarlospaco/3bfb24d157aed7952839#gistcomment-1597678

**Comment by humitos** [comment]
@juancarlospaco ¿podrías hacer un PR que sea compatible con lo que ya tenemos?

**Comment by humitos** [comment]
Usa Markdown, pero nos puede llevar a lo que necesitamos: https://github.com/javiereguiluz/easybook
